### ISSUE TITLE
Code in commentaar moet uit de master

### ISSUE THREAD

**Issue by eothein** [Timschotte/rubric-android#42]
Code die in commentaar staat moet van de master branch verwijderd worden. Bv. 

```
    //fun launchRubricsActivity(view: View) {
        //val intent = Intent(this, RubricsActivity::class.java)
        //startActivity(intent)
    //}
```

**Comment by StaelensC** [comment]
Gisteren is de master pas up-to-date gezet, develop branch stond al veel verder. Ik sluit deze issue nog niet af, omdat we de code best overlopen om te zien of alle comments er uit zijn
