### ISSUE TITLE
Het is interessant gebruik te maken van Dependency Injection

### ISSUE THREAD

**Issue by eothein** [Timschotte/rubric-android#45]
Veel code kan loosely coupled gemaakt worden door gebruik te maken van een DI framework. Ik raad bv. Koin aan.

**Comment by eothein** [comment]
Jullie maken trouwens gebruik van DI (Dagger2), maar dan niet overal?

**Comment by StaelensC** [comment]
Gebruik van Dagger2 is de norm in deze app. Gisteren is de master pas up-to-date gezet, develop branch stond al veel verder. Ik sluit deze issue nog niet af, omdat we de code best overlopen om te zien of Dagger2 effectief overal gebruikt wordt

**Comment by BertVermorgen** [comment]
alle referenties naar Anko zijn er uit.
