### ISSUE TITLE
⚠️ Anko is deprecated. Please see this page for more information.

### ISSUE THREAD

**Issue by eothein** [Timschotte/rubric-android#47]
In de code vind ik het gebruik van Anko terug. In de documentatie van Anko staat er 

> ⚠️ Anko is deprecated. Please see this page for more information. 

Het gebruik ervan is dus ten stelligste af te raden: het gebruik van co-routines daarentegen zoals aangereikt in de cursus Native Apps 1 is wel aan te raden.

**Comment by StaelensC** [comment]
Dit gaat om een oude versie, gisteren is de master up-to-date gezet
