### ISSUE TITLE
RxJava en Anko door elkaar gebruikt

### ISSUE THREAD

**Issue by eothein** [Timschotte/rubric-android#55]
Zie issue #47 rond gebruik van Anko. 

In issue #54 zie je code die dan opeen RxJava gebruikt i.p.v. Anko. Bedoeling is wel dat consistent de libraries gebruikt worden.

**Comment by StaelensC** [comment]
Issue's fixed, dit ging om een oude versie, gisteren is de master up-to-date gezet
